include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

default:
  interruptible: true
  image: python:3.12

.install__dev_packages:
  script: &install_dev_packages
    pip install poetry && poetry install --sync

.install_prod_packages:
  script: &install_prod_packages
    pip install poetry && poetry install --without dev --sync

stages:
  - check
  - test
  - build
  - publish

static-checks:
  stage: check
  script:
    - *install_dev_packages
    -  poetry run pre-commit run --all-files --config ./.pre-commit-config-ci.yaml # Runs static type checks, linting, and formatting

unit-tests:
  stage: test
  script:
    - *install_dev_packages
    - poetry run pytest

build:
  stage: build
  script:
    - docker build -t bluebrain/virtual-lab-manager:latest .

publish:
  stage: publish
  needs: ["build"]
  script:
    - echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin docker push bluebrain/virtual-lab-manager:latest

# build:
#   stage: check
#   script:
#     - *install_packages
#     - npm run build
#   except:
#     - develop
#     - main
