default_install_hook_types: [pre-push]
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.2
  hooks:
    # Run the linter.
    - id: ruff
      stages: [push]
    # Run the formatter.
    - id: ruff-format
      stages: [push]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        stages: [push]
