version: "3.9"

volumes:
  keycloak_data: {}
  vlm_data: {}

networks:
  keycloak_net: {}

services:
  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak-instance:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_FRONTEND_URL: http://localhost:8080
    depends_on:
      - keycloak-db
    command: 
      - start-dev
    ports:
      - "8081:8080"
    networks:
      - keycloak_net

  virtual-lab-db:
    image: postgres:latest
    container_name: vlm-db
    environment:
      POSTGRES_USER: vlm
      POSTGRES_PASSWORD: vlm
      PGDATA: vlm_data
      POSTGRES_DB: vlm
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vlm"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - vlm_data:/var/lib/postgresql/data
