[tool.poetry]
name = "virtual-labs"
version = "0.1.0"
description = ""
authors = ["Bilal Meddah <bilal.meddah@epfl.ch>", "Pavlo Getta <pavlo.getta@epfl.ch>", "Dinika Saxena <dinika.saxena@epfl.ch>"]
readme = "README.md"
packages = [{include = "virtual_labs"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["all"], version = "^0.110.0"}
uvicorn = "^0.27.1"
sqlalchemy = "^2.0.27"
uuid = "^1.30"
datetime = "^5.4"
python-dotenv = "^1.0.1"
psycopg2-binary = "^2.9.9"
loguru = "^0.7.2"
pydantic-settings = "^2.2.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.2.2"
mypy = "^1.8.0"
pre-commit = "^3.6.2"
pytest = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
