name: Publish main

on:
    push:
      branches:
        - main

jobs:
  publish-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker build -t bluebrain/obp-virtual-lab-api .

      - name: Publish To DockerHub
        run: |
          docker push bluebrain/obp-virtual-lab-api
