name: Pre-merge Review

on: [pull_request]

jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: pip install poetry && poetry install --sync
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run styling
        run: make style-check
      - name: Run type checks
        run: make type-check
      - name: Start services
        run: IS_CI="True" make init
      - name: Run tests
        run: make test
