name: Pre-merge Review

on: [pull_request]

jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install poetry && poetry install --sync
      - name: Run styling
        run: make style-check
      - name: Run type checks
        run: make type-check
      - name: Start services
        run: IS_CI="True" make init
      - name: Run tests
        run: make test
      - name: cleanup
        if: ${{ always() }}
        run: |
          docker compose -f env-prep/docker-compose-dev.yml -p vlm-project down --rmi all --volumes
          docker system prune --force --volumes